id: opecha:P008142
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS16402
  title: གནམ་ཆོས་ཐུགས་ཀྱི་གཏེར་ཁ།
  volume:
    df149b4adb504a799691b30813cdae1e:
      image_group_id: I8LS16416
      title: Volume 1 of gnam chos/
      volume_number: 1
      total_pages: 530
  author: ''
ebook_metadata:
  title: གནམ་ཆོས་ཐུགས་ཀྱི་གཏེར་ཁ།
  author: ''
  sku: P008142
  cover: cover.jpg
  layers:
  - pagination
