id: P008142
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:04:15.209773
source_metadata:
  id: bdr:W8LS16402
  title: གནམ་ཆོས་ཐུགས་ཀྱི་གཏེར་ཁ།
  author: ''
  volumes:
    2779b38b2b4d4b729c149c129db1efa1:
      image_group_id: I8LS16416
      title: ''
      volume_number: 1
      total_pages: 530
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
