id: IA4AB363A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T05:28:42+00:00'
last_modified: '2022-06-09T04:47:42.955690+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16402
  title: གནམ་ཆོས་ཐུགས་ཀྱི་གཏེར་ཁ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E298:
      image_group_id: I8LS16416
      title: ''
      total_pages: 530
      order: 1
      base_file: E298.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
